import type { StationHub } from '../types/index.ts';

export const MAJOR_HUBS: StationHub[] = [
  // 台北捷運站點
  {
    code: 'MRT_TPE_MAIN',
    type: 'MRT_STATION',
    name: '台北車站 (捷運站)',
    address: '台北市中正區忠孝西路一段49號',
    lat: 25.046255,
    lng: 121.517532,
    city: 'Taipei',
    country: 'TW',
  },
  {
    code: 'MRT_NANGANG',
    type: 'MRT_STATION',
    name: '南港展覽館站 (捷運站)',
    address: '台北市南港區南港路一段32號',
    lat: 25.055278,
    lng: 121.617222,
    city: 'Taipei',
    country: 'TW',
  },
  {
    code: 'MRT_BANQIAO',
    type: 'MRT_STATION',
    name: '板橋站 (捷運站)',
    address: '新北市板橋區文化路一段100號',
    lat: 25.013917,
    lng: 121.462778,
    city: 'New Taipei',
    country: 'TW',
  },

  // 台灣高鐵站點
  {
    code: 'THSR_TPE',
    type: 'HSR_STATION',
    name: '高鐵台北站',
    address: '台北市中正區北平西路3號',
    lat: 25.047924,
    lng: 121.517081,
    city: 'Taipei',
    country: 'TW',
  },
  {
    code: 'THSR_TXG',
    type: 'HSR_STATION',
    name: '高鐵台中站 (烏日)',
    address: '台中市烏日區高鐵東一路26號',
    lat: 24.111815,
    lng: 120.615754,
    city: 'Taichung',
    country: 'TW',
  },
  {
    code: 'THSR_ZUY',
    type: 'HSR_STATION',
    name: '高鐵左營站 (高雄)',
    address: '高雄市左營區高鐵路105號',
    lat: 22.687445,
    lng: 120.307556,
    city: 'Kaohsiung',
    country: 'TW',
  },

  // 國道高速公路樞紐與休息服務區 (汽車/自駕車順路面交節點)
  {
    code: 'HWY_ZHONGLI_REST',
    type: 'HIGHWAY_HUB',
    name: '國道一號中壢服務區',
    address: '桃園市中壢區內定里內定二街998-3號',
    lat: 24.995833,
    lng: 121.228611,
    city: 'Taoyuan',
    country: 'TW',
  },
  {
    code: 'HWY_HSINCHU_IC',
    type: 'HIGHWAY_HUB',
    name: '國道一號新竹科學園區交流道 (公道五路交會口)',
    address: '新竹市東區公道五路二段與園區二路口',
    lat: 24.795833,
    lng: 121.002778,
    city: 'Hsinchu',
    country: 'TW',
  },
  {
    code: 'HWY_QINGSHUI_REST',
    type: 'HIGHWAY_HUB',
    name: '國道三號清水服務區',
    address: '台中市清水區中社路東湖巷22號',
    lat: 24.288333,
    lng: 120.601944,
    city: 'Taichung',
    country: 'TW',
  },

  // 國際機場節點
  {
    code: 'AIR_TPE_T2',
    type: 'AIRPORT',
    name: '桃園國際機場 (第二航廈)',
    address: '桃園市大園區航站南路9號',
    lat: 25.077685,
    lng: 121.232822,
    city: 'Taoyuan',
    country: 'TW',
  },
  {
    code: 'AIR_TSA',
    type: 'AIRPORT',
    name: '台北松山機場',
    address: '台北市松山區敦化北路340-9號',
    lat: 25.069722,
    lng: 121.552500,
    city: 'Taipei',
    country: 'TW',
  },
  {
    code: 'AIR_HND',
    type: 'AIRPORT',
    name: '東京羽田國際機場 (Haneda HND)',
    address: 'Hanedakuko, Ota City, Tokyo 144-0041, Japan',
    lat: 35.549393,
    lng: 139.779839,
    city: 'Tokyo',
    country: 'JP',
  },
  {
    code: 'AIR_NRT',
    type: 'AIRPORT',
    name: '東京成田國際機場 (Narita NRT)',
    address: '1-1 Furugome, Narita, Chiba 282-0004, Japan',
    lat: 35.771987,
    lng: 140.392850,
    city: 'Tokyo',
    country: 'JP',
  },
];
